name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-application

    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to Docker Hub
      uses: actions/docker/cli@master
      with:
        args: push $secrets.DOCKER_USERNAME/my-application
